In [69]:
#Import Libraries

import pandas as pd
from pandas import DataFrame
import numpy as np

In [104]:
"""
I have defined a list with the 4 values and duplicated that to make the list bigger.
"""

my_list = [1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,
           137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,
           2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,
           1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,1,2,3,137.036,
           137.036,137.036,1,2,3,137.036,1,2,3,137.036,137.036,137.036,1,2,3,137.036,
           1,2,3,137.036,137.036,137.036]

In [96]:
#Convert the list to a dataframe

df = DataFrame(my_list, columns = ['numbers'])

In [ ]:
"""
If the data is in a file (for ex. CSV file), use this code

df = pd.read_csv(r'Path where you want to export the CSV file\File Name.csv')

"""

In [105]:
#View the data
print(df)

     numbers  mean  std dev  median
0       1.00  1.00     0.00    1.00
1       2.00  1.50     0.50    1.50
2       3.00  2.00     0.82    2.00
3     137.04 35.76    58.48    2.50
4       1.00 28.81    54.12    2.00
..       ...   ...      ...     ...
565     2.00 55.68    66.09    3.00
566     3.00 55.59    66.07    3.00
567   137.04 55.73    66.10    3.00
568   137.04 55.87    66.13    3.00
569   137.04 56.01    66.16    3.00

[570 rows x 4 columns]

In [102]:
#Code to get incremental mean, median and std dev 
try:
    df['mean']= df['numbers'].expanding().mean()
    df['std dev'] = df['numbers'].expanding().std(ddof=0)
    df['median'] = df['numbers'].expanding().median()
except:
    print('An error has occured. Please check the values in your list')

In [106]:
print(df)

     numbers  mean  std dev  median
0       1.00  1.00     0.00    1.00
1       2.00  1.50     0.50    1.50
2       3.00  2.00     0.82    2.00
3     137.04 35.76    58.48    2.50
4       1.00 28.81    54.12    2.00
..       ...   ...      ...     ...
565     2.00 55.68    66.09    3.00
566     3.00 55.59    66.07    3.00
567   137.04 55.73    66.10    3.00
568   137.04 55.87    66.13    3.00
569   137.04 56.01    66.16    3.00

[570 rows x 4 columns]

In [ ]:
"""
To save this data to a csv file

df.to_csv(r'Path where you want to store the exported CSV file\File Name.csv', index = False)

"""